### ISSUE TITLE
[Feature request] Allow cursor moving on `ainput`

### ISSUE THREAD

**Issue by RaulWCosta** [vxgmichel/aioconsole#119]
I'm currently developing a interactive CLI using Python's [Cmd class](https://docs.python.org/3/library/cmd.html).
I'm adapting it to get the input from the user asynchronously, and aioconsole came very handy for that!

However, contrary to Python's native `input`, aioconsole's `ainput` function does not allow users to move the cursor to edit the input on the middle.

`input`:

![Screenshot 2024-07-18 at 11 16 01](https://github.com/user-attachments/assets/cb870bdd-7231-404d-957e-512e4fd8d8f6)

`ainput`:

![Screenshot 2024-07-18 at 11 20 01](https://github.com/user-attachments/assets/022dacb6-88cf-401c-8f0f-738471349819)

**Comment by vxgmichel** [comment]
Hi @RaulWCosta,

It turns out this is pretty hard to do, as acknowdeldged in the [limitations](https://github.com/vxgmichel/aioconsole?tab=readme-ov-file#limitations) section of the README.

However, the `apython` script works around this issue by implementing something similar to [rlwrap](https://github.com/hanslub42/rlwrap). You can check this [rlwrap.py](https://github.com/vxgmichel/aioconsole/blob/main/aioconsole/rlwrap.py) module if you're curious.

FYI, there's one pure python project that does this correctly: [prompt-toolkit](https://pypi.org/project/prompt-toolkit/)
The proper way to handle this in `aioconsole` would be to add `prompt-toolkit` as a dependency, but this would be a major change to the project that I'm not willing to do for the moment.

Hope it helps :)

**Comment by RaulWCosta** [comment]
Hey @vxgmichel greatly appreciate the reply and the suggestions. I'll definitely checkout [prompt-toolkit](https://pypi.org/project/prompt-toolkit/).

Also, feel free to close this issue if you want :)
