### ISSUE TITLE
Recognize and load code from PYTHONSTARTUP envar

### ISSUE THREAD

**Issue by vEpiphyte** [vxgmichel/aioconsole#56]
Is it possible to add support for certain environment variables when starting a interactive instance of aioconsole, such as PYTHONSTARTUP ?

**Comment by vxgmichel** [comment]
Hi @vEpiphyte and thanks for the report!

Most python environment variables should already be supported. `PYTHONSTARTUP` is a bit different since it is dealt with only if python itself runs in interactive mode (which is not the case when running `apython`). This could easily be fixed by adding this code snippet from the [tutorial](https://docs.python.org/3/tutorial/appendix.html#the-interactive-startup-file) in the [run_apython](https://github.com/vxgmichel/aioconsole/blob/c5d2d23a5373deab561d738548e16c10ccc3b979/aioconsole/apython.py#L82) function:

```python
import os
filename = os.environ.get('PYTHONSTARTUP')
if filename and os.path.isfile(filename):
    with open(filename) as fobj:
        startup_file = fobj.read()
    exec(startup_file)
```
Feel free to submit a PR if you're interested, otherwise I'll do that later :)

**Comment by vEpiphyte** [comment]
@vxgmichel I'd be happy to throw together a PR to load PYTHONSTARTUP prior to entering the interactive loop.  The example code is similar to the the pymain_run_startup function (https://github.com/python/cpython/blob/3.7/Modules/main.c#L228).  I'd want to include a print or warning statement if the option is set and the file doesn't exist.  Would that work for you?

**Comment by vxgmichel** [comment]
>  Would that work for you?
That sounds great, thanks :)
