### ISSUE TITLE
Feature: Access locals of invoking program?

### ISSUE THREAD

**Issue by trimitri** [vxgmichel/aioconsole#6]
Dear Vincent,
very cool project indeed! I struggled with writing or finding something like this.

To interact with my running asyncio program though, I would need to access it's `locals`. I've read through the documentation and also searched in the code. It seems that the `AsynchronousConsole` class supports passing the current scope. Is it somehow possible to inject my locals into `apython.start_interactive_server()`?

Any way: thanks for your work!

**Comment by vxgmichel** [comment]
Thank you for your report!

> Is it somehow possible to inject my locals into aioconsole.start_interactive_server()?

It is, using the `factory` argument: 

```python
   factory = lambda streams=None: \
        aioconsole.AsynchronousConsole(
            locals={'a': 1}, streams=streams)
    server = await aioconsole.start_interactive_server(
        factory=factory,
        host='localhost',
        port=8000)
```

The `start_interactive_server` coroutine does not have a `locals` argument because it might not make sense in the context of another factory (such as `AsynchronousCli`).

Another way to achieve the same purpose is to use `InteractiveEventLoop`

```python
loop = aioconsole.InteractiveEventLoop(locals={'a': 1}, serve=('localhost', 8000))
asyncio.set_event_loop(loop)
```

Maybe we should add some kind of helper (e.g. `start_console_server`) that would fit your use case in a better way.

Also, note that the locals dictionary is going to be updated at runtime.

**Comment by trimitri** [comment]
The custom factory method works exactly as described and solves my problem. Thank you!
