### ISSUE TITLE
Module `aioconsole.code` might conflict with the `code` module from the standard library

### ISSUE THREAD

**Issue by ronaaronson** [vxgmichel/aioconsole#60]
I am running Python 3.6.4 under Windows 10 and when I try to import aioconsole I mmediately get the following error:

>>> import aioconsole
2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\aioconsole\__init__.py", line 7, in <module>
    from .code import AsynchronousConsole, interact
  File "C:\Program Files\Python36\lib\site-packages\aioconsole\code.py", line 36, in <module>
    class AsynchronousConsole(code.InteractiveConsole):
AttributeError: module 'code' has no attribute 'InteractiveConsole'

**Comment by vxgmichel** [comment]
Hi @ronaaronson and thanks for the report!

I think something is broken with your python path or standard library because the module in `site-packages\aioconsole\code.py` is meant to import the [code](https://docs.python.org/3.5/library/code.html) module from the standard library.

Somehow, python ends up importing the `aioconsole.code` module itself either because the `PYTHONPATH` is configured to find module within `site-packages\aioconsole\` first or because the `code` module is missing from the standard library. 

In any case, it was a bad idea to have a local module conflicting with another one from the standard library, as it hides the real problem. I'll rename the issue accordingly.

Thanks again!

**Comment by vxgmichel** [comment]
The fix will become available with v0.1.16, thanks for the report!

**Comment by vxgmichel** [comment]
[v0.1.16](https://github.com/vxgmichel/aioconsole/releases/tag/v0.1.16) is out!
