### ISSUE TITLE
Pressing ctrl-d when running interact(stop=False) in a loop causes unexpected behaviour

### ISSUE THREAD

**Issue by iExalt** [vxgmichel/aioconsole#65]
Using Python 3.8, aioconsole 0.1.16

Contrived example:
```
import asyncio

from aioconsole import interact


async def test():
    while True:
        await interact(stop=False)
        asyncio.sleep(1)

asyncio.run(test())

```

Expected behaviour:
- I'm running `await interact(stop=False)` in a `while True:` loop as I don't want the "debug console" to close on stray ctrl-d presses. 
- I expect that the console will quit, and after a short time another console will be ready to be interacted with

Observed behaviour:
- When I quit using `quit()` or `exit()` the next console spawns fine and I can interact with it perfectly fine
- When I quit using ctrl-d, the console startup message is spammed without any further interaction and I can't interact with the successive consoles at all

Output:
```
Python 3.8.0 (default, Oct 28 2019, 16:14:01)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
---
This console is running in an asyncio event loop.
It allows you to wait for coroutines using the 'await' syntax.
Try: await asyncio.sleep(1, result=3)
---
>>>
Python 3.8.0 (default, Oct 28 2019, 16:14:01)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
---
This console is running in an asyncio event loop.
It allows you to wait for coroutines using the 'await' syntax.
Try: await asyncio.sleep(1, result=3)
---
>>>
```
and so on and so forth

**Comment by vxgmichel** [comment]
@iExalt Interesting, thanks for the report!

I never thought about this use case, I'll have a look at it!

Also you forgot an `await` before `asyncio.sleep(1)` :)

**Comment by vxgmichel** [comment]
Here's the result of my investigation:

`Ctrl+D` sends an EOT to the terminal which ends up closing the stdin pipe. The reason why the startup message is spammed is because the `interact()` returns instantly since `stdin` is closed. Now you might wonder why this does not happend when using `IPython.embed()` for instance. The reason is that `IPython` uses `prompt-toolkit` which sets the terminal to raw mode. In this mode, the terminal simply forwards the control character (such as `Ctrl+D`) which allows `prompt-toolkit` to set custom handlers for those characters.

There's not much we can do here, apart from re-writing `aioconsole` on top of `prompt-toolkit`. This would an interesting project, especially since the version 3 supports asyncio natively. It would be great for other reasons, in particular it would bring better readline support for both local and remote console. Unfortunately, I don't have time to work on project like this one at the moment.

One thing I could do though is to manage the case where one tries to interact with a closed pipe, maybe raising an exception. What do you think?

**Comment by iExalt** [comment]
stdin and EOT is above my paygrade, but would it be possible to "reattach" the stdin pipe upon receiving the "PipeClosed" exception?

Thanks for the `prompt-toolkit` tip, it looks like they already have an analogue to `aioconsole.interact` with their `ptpython` library [here](https://github.com/prompt-toolkit/ptpython/blob/master/examples/asyncio-python-embed.py).

**Comment by vxgmichel** [comment]
> stdin and EOT is above my paygrade, but would it be possible to "reattach" the stdin pipe upon receiving the "PipeClosed" exception?

As far as I know, no it's not possible to reopen a close stream.

> Thanks for the prompt-toolkit tip, it looks like they already have an analogue to aioconsole.interact with their ptpython library here.

Right! I'll add it to the alternative list in #52 :)

I'll close the issue as a `wontfix`, feel free to re-open it if you can think of an improvement on the current behavior.

Thanks again!
