### ISSUE TITLE
Can't use ainput within apython

### ISSUE THREAD

**Issue by lilydjwg** [vxgmichel/aioconsole#8]

**Comment by vxgmichel** [comment]
Thanks for your report!

`Ctrl-D` is actually supposed to be supported, as stated in the [docs](http://aioconsole.readthedocs.io/en/latest/#asynchronous-console):

> The console also supports Ctrl-C and Ctrl-D signals

I can confirm it works on my linux setup with python 3.6 and aioconsole 0.1.3.

Could you provide more information about the system you're using?

**Comment by lilydjwg** [comment]
I've tried again .It works at first. But after I called ainput, I'm stuck.

```
>>> from aioconsole.stream import ainput
>>> await ainput('>> ') 
>> lksdjf
lksdjf

>>>
```

**Comment by vxgmichel** [comment]
Oh I see! That has to do with the fact that using `ainput` within an asynchronous console will remove the `stdin` file descriptor from the event loop at the end. The console won't be notified of any user input after that. Only `Ctrl+C` will work, since it's goes through the signaling mechanism. For some reasons, this is not the case for `Ctrl+D` (see [this part of the code](https://github.com/vxgmichel/aioconsole/blob/master/aioconsole/code.py#L191-L192)).

Do you see an actual use case for using `ainput` within an asynchronous console?

**Comment by lilydjwg** [comment]
> Do you see an actual use case for using ainput within an asynchronous console?

Not yet. I was testing. `Ctrl-C` only raises a KeyboardInterrupted exception, I have to use `Ctrl-\` to quit. Maybe tell users don't try `ainput` at the prompt?

**Comment by vxgmichel** [comment]
Fixed! It's now ok to use `ainput` from an asynchronous console (local or served). This will become visible with version 0.1.9. Thanks a again for the report!
